<table class="table farsi ">
    <tbody>
    <tr>
        <td>{{Lang::get('words.first_name')}}</td>
        <td>
            {{$currentUser->first_name}}
        </td>
    </tr>
    <tr>
        <td>{{Lang::get('words.last_name')}}</td>
        <td>
            {{$currentUser->last_name}}
        </td>
    </tr>
    <tr>
        <td>{{Lang::get('words.country_of_residence')}}</td>
        <td>
            {{country($currentUser->country_of_residence)}}
        </td>
    </tr>
    <tr>
        <td>{{Lang::get('words.mobile_number')}}</td>
        <td>
            {{$currentUser->mobile_number}}
        </td>
    </tr>
    <tr>
        <td>{{Lang::get('words.email_address')}}</td>
        <td>
            {{$currentUser->email_address}}
        </td>
    </tr>
    <tr>
        <td>{{Lang::get('words.timezone')}}</td>
        <td>
            {{$currentUser->timezone}}
        </td>
    </tr>
    <tr>
        <td>{{Lang::get('words.profile_color')}}</td>
        <td>{{$currentUser->profile_color}}</td>
    </tr>
    </tbody>
</table>